server:
  port: 8000
eureka:
  instance:      # eureak实例定义
    hostname: eureka1  # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 100  #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation:  false #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client:
    fetch-registry: false #是否要从注册中心获取注册信息
    register-with-eureka: false #是否注册到euraka
    service-url:
      defaultZone: http://admin:admin@eureka1:8000/eureka,http://admin:admin@eureka2:8001/eureka,http://admin:admin@eureka3:8002/eureka
spring:
  security:
    user:
      name: admin
      password: admin
