server:
 port: 8080
mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml
spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
   url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8 # 数据库连接地址
   username: root # 数据库用户名
   password: mqpass0o0 # 数据库连接密码
 application:
   name: bootcloud-producer  #euraka Application名
# security:
#   user:
#     name: admin # 认证用户名
#     password: admin  # 认证密码
#     roles:
#      - USER  # 认证密码
logging:
  level:
    cn.java.cloud.mapper: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1:8000/eureka,http://admin:admin@eureka2:8001/eureka,http://admin:admin@eureka3:8002/eureka
#      defaultZone: http://admin:admin@localhost:8000/eureka
      #defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: bootcloud-producer
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 设置心跳的时间间隔（默认是30秒）

info:
  app.name: bootcloud-producer
  company.name: SpringCloud+SpringBoot
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
